tt

diff --git a/test.jenkinsfile b/test.jenkinsfile
--- a/test.jenkinsfile
+++ b/test.jenkinsfile
@@ -17,24 +17,27 @@ pipeline {
         }
         stage('Docker Run'){
             steps {
-                script {
-                    docker.image("test-jenkins:0.1").withRun(){ c->
-                        sh "docker logs --follow ${c.id} > runner.log" 
+                step{
+                    script {
+                        docker.image("test-jenkins:0.1").withRun(){ c->
+                            sh "docker logs --follow ${c.id} > runner.log" 
+                        }
                     }
                 }
-            }
-            steps {
-                script {
-                    sh """#!/bin/bash
-                        if grep -e "All Tests Passed! Congratulations!!!" runner.log; then
-                            echo "Tests Pass"
-                            exit 0
-                        else
-                            echo "Tests Fail"
-                            exit 1
-                        fi
-                    """
+                step{
+                    script {
+                        sh """#!/bin/bash
+                            if grep -e "All Tests Passed! Congratulations!!!" runner.log; then
+                                echo "Tests Pass"
+                                exit 0
+                            else
+                                echo "Tests Fail"
+                                exit 1
+                            fi
+                        """
+                    }
                 }
+                
             }
         }
     }
