foreign syntax for me

diff --git a/test.jenkinsfile b/test.jenkinsfile
--- a/test.jenkinsfile
+++ b/test.jenkinsfile
@@ -17,26 +17,23 @@ pipeline {
         }
         stage('Docker Run'){
             steps {
-                step{
-                    script {
-                        docker.image("test-jenkins:0.1").withRun(){ c->
-                            sh "docker logs --follow ${c.id} > runner.log" 
-                        }
+                script {
+                    docker.image("test-jenkins:0.1").withRun(){ c->
+                        sh "docker logs --follow ${c.id} > runner.log" 
                     }
                 }
-                step{
-                    script {
-                        sh """#!/bin/bash
-                            if grep -e "All Tests Passed! Congratulations!!!" runner.log; then
-                                echo "Tests Pass"
-                                exit 0
-                            else
-                                echo "Tests Fail"
-                                exit 1
-                            fi
-                        """
-                    }
+                script {
+                    sh """#!/bin/bash
+                        if grep -e "All Tests Passed! Congratulations!!!" runner.log; then
+                            echo "Tests Pass"
+                            exit 0
+                        else
+                            echo "Tests Fail"
+                            exit 1
+                        fi
+                    """
                 }
+
                 
             }
         }
